---
abstract: 'A small, simple, correct HTTP/1.1 client'
author:
  - 'Christian Hansen <chansen@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: '0'
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  IO::Dir: '0'
  IO::File: '0'
  IO::Socket::INET: '0'
  IPC::Cmd: '0'
  List::Util: '0'
  Test::More: '0.96'
  open: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  HTTP::Tiny:
    file: lib/HTTP/Tiny.pm
    version: '0.043'
recommends:
  HTTP::CookieJar: '0.001'
  IO::Socket::IP: '0.25'
  IO::Socket::SSL: '1.42'
  Mozilla::CA: '20120823'
  Net::SSLeay: '1.49'
requires:
  Carp: '0'
  Fcntl: '0'
  IO::Socket: '0'
  MIME::Base64: '0'
  Time::Local: '0'
  bytes: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chansen/p5-http-tiny/issues
  homepage: https://github.com/chansen/p5-http-tiny
  repository: https://github.com/chansen/p5-http-tiny.git
version: '0.043'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Alan Gardner <gardner@pythian.com>'
  - 'Alessandro Ghedini <al3xbio@gmail.com>'
  - 'Brad Gilbert <bgills@cpan.org>'
  - 'Chris Nehren <apeiron@cpan.org>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'Claes Jakobsson <claes@surfar.nu>'
  - 'Clinton Gormley <clint@traveljury.com>'
  - 'Craig Berry <cberry@cpan.org>'
  - 'David Mitchell <davem@iabyn.com>'
  - 'Edward Zborowski <ed@rubensteintech.com>'
  - 'Jess Robinson <castaway@desert-island.me.uk>'
  - 'Lukas Eklund <leklund@gmail.com>'
  - 'Martin J. Evans <mjegh@ntlworld.com>'
  - 'Martin-Louis Bright <mlbright@gmail.com>'
  - 'Mike Doherty <doherty@cpan.org>'
  - 'Petr Písař <ppisar@redhat.com>'
  - 'Serguei Trouchelle <stro@cpan.org>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Tony Cook <tony@develop-help.com>'
