---
abstract: 'A small, simple, correct HTTP/1.1 client'
author:
  - 'Christian Hansen <chansen@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  File::Temp: 0
  IO::Dir: 0
  IO::File: 0
  IO::Socket::INET: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  HTTP::Tiny:
    file: lib/HTTP/Tiny.pm
    version: 0.007
  HTTP::Tiny::Handle:
    file: lib/HTTP/Tiny.pm
    version: 0.007
requires:
  Carp: 0
  Errno: 0
  IO::Socket: 0
  Time::Local: 0
  perl: 5.006
resources:
  homepage: http://github.com/dagolden/p5-http-tiny/tree
  repository: git://github.com/dagolden/p5-http-tiny.git
version: 0.007
