use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004003
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Alessandro
CA's
CAcert
Claes
EINTR
Eklund
Ghedini
IPv
Jakobsson
Lukas
Nehren
SSL
Serguei
Trouchelle
Weyl
Zborowski
chunked
iteratively
redirections
timestamp
Christian
Hansen
chansen
David
Golden
dagolden
lib
HTTP
Tiny
